spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://dpg-d7iq410sfn5c738lhqe0-a.oregon-postgres.render.com/site_agent_db?sslmode=require
    username: site_agent_db_user
    password: RzesLBNCGv6pAs3rEfoPHdluxnVZPUaM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: never  # 이 줄 추가!

jwt:
  secret: localdevsecretkey1234567890abcdef
  expiration: 86400000

supabase:
  url: https://mnychkcbsfnhepqzdked.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ueWNoa2Nic2ZuaGVwcXpka2VkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Njg0NDA1MywiZXhwIjoyMDkyNDIwMDUzfQ.XEXWGUy8peJnfoz8gr5qiGkRHgbwTLKs0Foc5pIBYbo
  bucket: site-pdfs

kakao:
  client-id: 4e6d06198d4374e6a5422f096bd2476b
  client-secret: uDbD6rDG7z0JqRN4P7LzHjaeO5b9CEjj
  redirect-uri: http://localhost:3000/auth/kakao/callback

fastapi:
  url: http://localhost:8000

server:
  port: 8080